name: sm_lints
description: "Recommended lints for Flutter apps, packages, and plugins to encourage good coding practices"
homepage: https://github.com/shay-wong/flutter_sm_packages/tree/main/sm_lints
issue_tracker: https://github.com/shay-wong/flutter_sm_packages/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+sm_lints%22
version: 2.0.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter_lints: ">=6.0.0 <7.0.0"

topics:
  - lints
