name: sm_network
description: "A Flutter networking library that provides a simple and convenient
  way to access network resources."
homepage: https://github.com/shay-wong/flutter_sm_packages
repository: https://github.com/shay-wong/flutter_sm_packages/tree/main/sm_network
issue_tracker: https://github.com/shay-wong/flutter_sm_packages/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+sm_network%22
version: 1.3.0-dev

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.24.5"

dependencies:
  dio: ">=5.8.0 <6.0.0"
  flutter:
    sdk: flutter
  json_annotation: ">=4.9.0 <5.0.0"
  meta: ">=1.15.0 <2.0.0"

dev_dependencies:
  build_runner: ">=2.4.13 <3.0.0"
  flutter_test:
    sdk: flutter
  http_mock_adapter: ">=0.6.1 <0.7.0"
  json_serializable: ">=6.9.0 <7.0.0"
  sm_lints: ">=2.0.0 <3.0.0"

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
