name: peek
description: "A Flutter debugging inspection tool."
homepage: https://github.com/shay-wong/flutter_sm_packages/tree/main/peek
issue_tracker: https://github.com/shay-wong/flutter_sm_packages/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+peek%22
version: 0.0.1

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.24.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ">=4.5.2 <5.0.0"
  shared_preferences: ">=2.5.3 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  sm_lints: ">=0.0.1 <3.0.0"

flutter:
  uses-material-design: true

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
