name: example
description: A project that showcases how to enable the recommended lints for Flutter apps, packages, and plugins.

publish_to: none

environment:
  sdk: ^3.8.0

dev_dependencies:
  sm_lints:
    path: ../
